/**
 * MCP ↔ REST API parity matrix.
 *
 * The Rokki product principle (CLAUDE.md, "Non-negotiables"): every
 * feature available in the UI is available via API and MCP tool. This
 * file is the source of truth for whether that holds today.
 *
 * Each row is a logical resource action ("create task", "list files in
 * a folder"). For each action we record:
 *   - the API endpoint(s) that satisfy it (path + method),
 *   - the MCP tool that satisfies it (or null),
 *   - a coverage label and gap note.
 *
 * Used by:
 *   - /admin/mcp page (renders this as a dense matrix)
 *   - docs/12_MCP_PARITY.md (regenerated by hand from the same data)
 *
 * When you add a new MCP tool, update this file. When you add a new
 * API endpoint, add a row here even if there's no MCP yet — that's the
 * whole point of the audit.
 */

export type ParityStatus =
  /** API and MCP both implement it (read OR write parity present). */
  | "present"
  /** Read tool exists, but corresponding write/mutation tool is missing
      (or vice versa). The matrix uses yellow for these. */
  | "partial"
  /** API exists, no MCP equivalent. The high-priority gaps. */
  | "missing"
  /** Admin/internal-only — intentionally not exposed via MCP. */
  | "admin-only";

export type Resource =
  | "auth"
  | "spaces"
  | "terminals"
  | "tasks"
  | "files"
  | "markets"
  | "folders"
  | "comments"
  | "members"
  | "search"
  | "ask"
  | "tools"
  | "approvals"
  | "activity"
  | "notifications"
  | "messages"
  | "calendar"
  | "drawings"
  | "share-links"
  | "tokens"
  | "api-keys"
  | "flags"
  | "announcements"
  | "vendors"
  | "depth-modules"
  | "admin"
  | "health";

export type Priority = "high" | "medium" | "low";

export interface ParityRow {
  /** Logical resource (groups rows in the doc and matrix). */
  resource: Resource;
  /** What the user can do (UI-facing verb). */
  action: string;
  /** REST endpoint(s). Empty string if action exists only via MCP. */
  apiEndpoints: string[];
  /** MCP tool name, or null if no equivalent exists. */
  mcpTool: string | null;
  /** Coverage label. */
  status: ParityStatus;
  /** Free-text note explaining the gap (or "" if none). */
  note: string;
  /** Recommended priority for closing the gap (only meaningful when
   *  status !== "present"). */
  priority?: Priority;
}

/**
 * The audit. Add a row per API endpoint or MCP tool, sorted by
 * resource then by action.
 *
 * Last reconciled: 2026-06-17 against:
 *   - apps/web/src/app/api/v1/**\/route.ts (REST surface)
 *   - apps/mcp-server/src/tools.ts + markets-tools.ts (MCP tool registry)
 */
export const PARITY_ROWS: ParityRow[] = [
  // ----- auth -----
  {
    resource: "auth",
    action: "Send magic link",
    apiEndpoints: ["POST /v1/auth/send-link"],
    mcpTool: null,
    status: "admin-only",
    note: "MCP clients authenticate with bearer tokens; magic-link is web-only.",
  },
  {
    resource: "auth",
    action: "Password login",
    apiEndpoints: ["POST /v1/auth/password-login"],
    mcpTool: null,
    status: "admin-only",
    note: "Browser-only flow; MCP tokens are minted via /v1/me/tokens.",
  },
  {
    resource: "auth",
    action: "Sign out",
    apiEndpoints: ["POST /v1/auth/sign-out"],
    mcpTool: null,
    status: "admin-only",
    note: "Cookie-only.",
  },
  {
    resource: "auth",
    action: "List accounts",
    apiEndpoints: ["GET /v1/auth/accounts"],
    mcpTool: null,
    status: "admin-only",
    note: "Multi-account ring is a browser session concept.",
  },
  {
    resource: "auth",
    action: "Get current session",
    apiEndpoints: ["GET /v1/me"],
    mcpTool: null,
    status: "missing",
    note: "MCP exposes session via tools/list initialize, but no rokki_me tool. Useful for clients to discover scopes / current user.",
    priority: "medium",
  },

  // ----- spaces -----
  {
    resource: "spaces",
    action: "List spaces",
    apiEndpoints: ["GET /v1/orgs"],
    mcpTool: "rokki_list_spaces",
    status: "present",
    note: "",
  },
  {
    resource: "spaces",
    action: "Create space",
    apiEndpoints: ["POST /v1/orgs"],
    mcpTool: "rokki_create_space",
    status: "present",
    note: "",
  },
  {
    resource: "spaces",
    action: "Get space",
    apiEndpoints: ["GET /v1/orgs/:slug"],
    mcpTool: null,
    status: "missing",
    note: "rokki_list_spaces returns the row but there's no detail tool. Add rokki_get_space (members, terminals count, settings).",
    priority: "medium",
  },
  {
    resource: "spaces",
    action: "Update space",
    apiEndpoints: ["PATCH /v1/orgs/:slug"],
    mcpTool: null,
    status: "missing",
    note: "Settings/branding edits not exposed.",
    priority: "low",
  },
  {
    resource: "spaces",
    action: "List space members",
    apiEndpoints: ["GET /v1/orgs/:slug/members"],
    mcpTool: "rokki_list_space_members",
    status: "present",
    note: "",
  },
  {
    resource: "spaces",
    action: "Invite to space",
    apiEndpoints: ["POST /v1/orgs/:slug/members"],
    mcpTool: "rokki_invite_to_space",
    status: "present",
    note: "",
  },
  {
    resource: "spaces",
    action: "Update member role",
    apiEndpoints: ["PATCH /v1/orgs/:slug/members/:userId"],
    mcpTool: null,
    status: "missing",
    note: "No tool to promote/demote space members.",
    priority: "medium",
  },
  {
    resource: "spaces",
    action: "Remove member",
    apiEndpoints: ["DELETE /v1/orgs/:slug/members/:userId"],
    mcpTool: null,
    status: "missing",
    note: "No tool to remove a space member.",
    priority: "medium",
  },
  {
    resource: "spaces",
    action: "List vendors",
    apiEndpoints: ["GET /v1/orgs/:slug/vendors"],
    mcpTool: null,
    status: "missing",
    note: "Construction-vertical vendor directory; AI agent should be able to read it.",
    priority: "low",
  },

  // ----- terminals -----
  {
    resource: "terminals",
    action: "List terminals",
    apiEndpoints: ["GET /v1/projects"],
    mcpTool: "rokki_list_terminals",
    status: "present",
    note: "",
  },
  {
    resource: "terminals",
    action: "Create terminal",
    apiEndpoints: ["POST /v1/projects"],
    mcpTool: "rokki_create_terminal",
    status: "present",
    note: "",
  },
  {
    resource: "terminals",
    action: "Get terminal",
    apiEndpoints: ["GET /v1/projects/:ticker"],
    mcpTool: null,
    status: "partial",
    note: "rokki_summarize_terminal exists but returns an LLM-generated narrative, not a structured object. Add rokki_get_terminal for the structured detail.",
    priority: "medium",
  },
  {
    resource: "terminals",
    action: "Update terminal",
    apiEndpoints: ["PATCH /v1/projects/:ticker"],
    mcpTool: "rokki_update_terminal",
    status: "present",
    note: "",
  },
  {
    resource: "terminals",
    action: "Archive terminal",
    apiEndpoints: ["DELETE /v1/projects/:ticker"],
    mcpTool: null,
    status: "missing",
    note: "rokki_update_terminal can flip status, but no clean archive verb.",
    priority: "low",
  },
  {
    resource: "terminals",
    action: "List terminal members",
    apiEndpoints: ["GET /v1/projects/:ticker/members"],
    mcpTool: "rokki_list_members",
    status: "present",
    note: "",
  },
  {
    resource: "terminals",
    action: "Invite terminal member",
    apiEndpoints: ["POST /v1/projects/:ticker/members"],
    mcpTool: "rokki_invite_member",
    status: "present",
    note: "",
  },
  {
    resource: "terminals",
    action: "Update terminal member role",
    apiEndpoints: ["PATCH /v1/projects/:ticker/members/:userId"],
    mcpTool: null,
    status: "missing",
    note: "No tool to change a terminal member's role.",
    priority: "medium",
  },
  {
    resource: "terminals",
    action: "Remove terminal member",
    apiEndpoints: ["DELETE /v1/projects/:ticker/members/:userId"],
    mcpTool: null,
    status: "missing",
    note: "No tool to remove a terminal member.",
    priority: "medium",
  },
  {
    resource: "terminals",
    action: "Construction depth: budget",
    apiEndpoints: ["GET /v1/projects/:ticker/budget"],
    mcpTool: null,
    status: "missing",
    note: "Construction-template depth module. AI assistant for HELIOS deals would want this.",
    priority: "high",
  },
  {
    resource: "terminals",
    action: "Construction depth: schedule",
    apiEndpoints: ["GET /v1/projects/:ticker/schedule"],
    mcpTool: null,
    status: "missing",
    note: "Construction-template depth module.",
    priority: "high",
  },
  {
    resource: "terminals",
    action: "Construction depth: permits",
    apiEndpoints: ["GET /v1/projects/:ticker/permits"],
    mcpTool: null,
    status: "missing",
    note: "Construction-template depth module.",
    priority: "high",
  },
  {
    resource: "terminals",
    action: "Briefing",
    apiEndpoints: ["GET /v1/briefing"],
    mcpTool: "rokki_what_changed",
    status: "partial",
    note: "rokki_what_changed covers terminal-scoped change summary; the dashboard /v1/briefing endpoint is broader (across all spaces). No equivalent broad MCP tool.",
    priority: "medium",
  },

  // ----- tasks -----
  {
    resource: "tasks",
    action: "List tasks",
    apiEndpoints: ["GET /v1/projects/:ticker/tasks"],
    mcpTool: "rokki_list_tasks",
    status: "present",
    note: "",
  },
  {
    resource: "tasks",
    action: "Create task",
    apiEndpoints: ["POST /v1/projects/:ticker/tasks"],
    mcpTool: "rokki_create_task",
    status: "present",
    note: "",
  },
  {
    resource: "tasks",
    action: "Get task",
    apiEndpoints: [
      "GET /v1/tasks/:id",
      "GET /v1/tasks/by-seq/:ticker/:seq",
    ],
    mcpTool: null,
    status: "missing",
    note: "Spec lists rokki_get_task in docs/03_MCP.md §3.4.4 but no implementation. AI workflow that wants full task body + comments needs this.",
    priority: "high",
  },
  {
    resource: "tasks",
    action: "Update task",
    apiEndpoints: ["PATCH /v1/tasks/:id"],
    mcpTool: "rokki_update_task",
    status: "present",
    note: "",
  },
  {
    resource: "tasks",
    action: "Complete task",
    apiEndpoints: ["POST /v1/tasks/:id/complete"],
    mcpTool: "rokki_complete_task",
    status: "present",
    note: "",
  },
  {
    resource: "tasks",
    action: "Delete task",
    apiEndpoints: ["DELETE /v1/tasks/:id"],
    mcpTool: "rokki_delete_task",
    status: "present",
    note: "",
  },
  {
    resource: "tasks",
    action: "Manage assignees",
    apiEndpoints: [
      "POST /v1/tasks/:id/assignees",
      "DELETE /v1/tasks/:id/assignees/:userId",
    ],
    mcpTool: null,
    status: "partial",
    note: "rokki_create_task and rokki_update_task can set assignees at create/update; no dedicated add/remove tool. Acceptable for now.",
    priority: "low",
  },
  {
    resource: "tasks",
    action: "Manage dependencies",
    apiEndpoints: ["POST /v1/tasks/:id/dependencies"],
    mcpTool: null,
    status: "missing",
    note: "No way to wire up task dependencies via MCP.",
    priority: "medium",
  },
  {
    resource: "tasks",
    action: "Manage subtasks",
    apiEndpoints: [
      "GET/POST /v1/tasks/:id/subtasks",
      "PATCH/DELETE /v1/tasks/:id/subtasks/:subtaskId",
    ],
    mcpTool: null,
    status: "missing",
    note: "Tier-1 task feature shipped 2026-04-27; no MCP coverage yet.",
    priority: "high",
  },
  {
    resource: "tasks",
    action: "Manage watchers",
    apiEndpoints: [
      "POST /v1/tasks/:id/watchers",
      "DELETE /v1/tasks/:id/watchers/:userId",
    ],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool to add/remove watchers.",
    priority: "medium",
  },
  {
    resource: "tasks",
    action: "Task comments (alias)",
    apiEndpoints: [
      "GET/POST /v1/tasks/:id/comments",
      "PATCH/DELETE /v1/tasks/:id/comments/:commentId",
    ],
    mcpTool: "rokki_comment",
    status: "present",
    note: "rokki_comment + rokki_list_comments cover the underlying comments API.",
  },

  // ----- files -----
  {
    resource: "files",
    action: "List files",
    apiEndpoints: ["GET /v1/projects/:ticker/files"],
    mcpTool: "rokki_list_files",
    status: "present",
    note: "",
  },
  {
    resource: "files",
    action: "Read file content",
    apiEndpoints: ["GET /v1/files/:id"],
    mcpTool: "rokki_read_file",
    status: "present",
    note: "",
  },
  {
    resource: "files",
    action: "Upload file",
    apiEndpoints: ["POST /v1/files/:id/signed-url"],
    mcpTool: null,
    status: "missing",
    note: "Spec lists rokki_upload_file in docs/03_MCP.md §3.4.10; not implemented. Highest-impact write gap.",
    priority: "high",
  },
  {
    resource: "files",
    action: "Download file",
    apiEndpoints: ["GET /v1/files/:id/download"],
    mcpTool: null,
    status: "partial",
    note: "rokki_read_file returns excerpts. No tool returns a download URL for the binary.",
    priority: "medium",
  },
  {
    resource: "files",
    action: "Rename file",
    apiEndpoints: ["PATCH /v1/files/:id"],
    mcpTool: "rokki_rename_file",
    status: "present",
    note: "",
  },
  {
    resource: "files",
    action: "Move file",
    apiEndpoints: ["PATCH /v1/files/:id"],
    mcpTool: "rokki_move_file",
    status: "present",
    note: "",
  },
  {
    resource: "files",
    action: "Duplicate file",
    apiEndpoints: ["POST /v1/files/:id/duplicate"],
    mcpTool: "rokki_duplicate_file",
    status: "present",
    note: "",
  },
  {
    resource: "files",
    action: "Delete (trash) file",
    apiEndpoints: ["DELETE /v1/files/:id"],
    mcpTool: "rokki_delete_file",
    status: "present",
    note: "",
  },
  {
    resource: "files",
    action: "Restore from trash",
    apiEndpoints: ["POST /v1/files/:id/restore"],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool to undo a delete.",
    priority: "low",
  },
  {
    resource: "files",
    action: "Permanent delete",
    apiEndpoints: ["DELETE /v1/files/:id/permanent"],
    mcpTool: null,
    status: "admin-only",
    note: "Owner-only destructive action; intentionally not exposed via MCP.",
  },
  {
    resource: "files",
    action: "Create share link",
    apiEndpoints: ["POST /v1/files/:id/share-links"],
    mcpTool: null,
    status: "missing",
    note: "Useful for AI to generate a shareable link to a doc.",
    priority: "medium",
  },

  // ----- folders -----
  {
    resource: "folders",
    action: "List folders",
    apiEndpoints: ["GET /v1/projects/:ticker/folders"],
    mcpTool: null,
    status: "missing",
    note: "rokki_list_files returns paths but no tool returns the folder tree directly.",
    priority: "medium",
  },
  {
    resource: "folders",
    action: "Create folder",
    apiEndpoints: ["POST /v1/projects/:ticker/folders"],
    mcpTool: "rokki_create_folder",
    status: "present",
    note: "",
  },
  {
    resource: "folders",
    action: "Rename folder",
    apiEndpoints: ["PATCH /v1/folders/:id"],
    mcpTool: "rokki_rename_folder",
    status: "present",
    note: "",
  },
  {
    resource: "folders",
    action: "Delete folder",
    apiEndpoints: ["DELETE /v1/folders/:id"],
    mcpTool: "rokki_delete_folder",
    status: "present",
    note: "",
  },
  {
    resource: "folders",
    action: "Duplicate folder",
    apiEndpoints: ["POST /v1/folders/:id/duplicate"],
    mcpTool: null,
    status: "missing",
    note: "Companion to rokki_duplicate_file. Useful for templating.",
    priority: "low",
  },

  // ----- comments -----
  {
    resource: "comments",
    action: "List comments",
    apiEndpoints: ["GET /v1/comments"],
    mcpTool: "rokki_list_comments",
    status: "present",
    note: "",
  },
  {
    resource: "comments",
    action: "Post comment",
    apiEndpoints: ["POST /v1/comments"],
    mcpTool: "rokki_comment",
    status: "present",
    note: "",
  },
  {
    resource: "comments",
    action: "Edit comment",
    apiEndpoints: ["PATCH /v1/comments/:id"],
    mcpTool: null,
    status: "missing",
    note: "No tool to edit a comment after posting.",
    priority: "low",
  },
  {
    resource: "comments",
    action: "Delete comment",
    apiEndpoints: ["DELETE /v1/comments/:id"],
    mcpTool: null,
    status: "missing",
    note: "No tool to delete a comment.",
    priority: "low",
  },

  // ----- search & ask -----
  {
    resource: "search",
    action: "Cross-terminal search",
    apiEndpoints: ["POST /v1/search"],
    mcpTool: "rokki_search",
    status: "present",
    note: "",
  },
  {
    resource: "ask",
    action: "Ask question over terminal data",
    apiEndpoints: [],
    mcpTool: "rokki_ask_project",
    status: "present",
    note: "MCP-only — no REST equivalent. Spec mentions POST /v1/projects/:ticker/ask but that endpoint is not yet implemented.",
  },

  // ----- activity -----
  {
    resource: "activity",
    action: "Recent activity",
    apiEndpoints: [],
    mcpTool: "rokki_recent_activity",
    status: "partial",
    note: "MCP tool exists. REST endpoints listed in docs/02_API.md §2.12 (/v1/projects/:ticker/activity, /v1/me/activity) are NOT implemented. UI reads via Supabase realtime instead — see /admin/activity.",
    priority: "medium",
  },

  // ----- notifications -----
  {
    resource: "notifications",
    action: "List notifications",
    apiEndpoints: ["GET /v1/notifications"],
    mcpTool: "rokki_notifications",
    status: "present",
    note: "",
  },
  {
    resource: "notifications",
    action: "Mark notifications read",
    apiEndpoints: ["POST /v1/notifications"],
    mcpTool: "rokki_mark_notifications_read",
    status: "present",
    note: "",
  },
  {
    resource: "notifications",
    action: "Push subscriptions (web push)",
    apiEndpoints: ["GET/POST /v1/me/push-subscriptions"],
    mcpTool: null,
    status: "admin-only",
    note: "Browser-only feature.",
  },

  // ----- messages -----
  {
    resource: "messages",
    action: "List threads",
    apiEndpoints: ["GET /v1/messages/threads"],
    mcpTool: null,
    status: "missing",
    note: "Direct messaging not yet exposed via MCP.",
    priority: "medium",
  },
  {
    resource: "messages",
    action: "Create thread",
    apiEndpoints: ["POST /v1/messages/threads"],
    mcpTool: null,
    status: "missing",
    note: "Direct messaging not yet exposed via MCP.",
    priority: "medium",
  },
  {
    resource: "messages",
    action: "Get thread / send message",
    apiEndpoints: [
      "GET /v1/messages/threads/:id",
      "POST /v1/messages/threads/:id",
    ],
    mcpTool: null,
    status: "missing",
    note: "AI assistant should be able to read a DM thread + reply.",
    priority: "medium",
  },

  // ----- tools (custom tool marketplace) -----
  {
    resource: "tools",
    action: "List tools",
    apiEndpoints: ["GET /v1/tools"],
    mcpTool: "rokki_list_tools",
    status: "present",
    note: "",
  },
  {
    resource: "tools",
    action: "Get tool detail",
    apiEndpoints: ["GET /v1/tools/:slug"],
    mcpTool: null,
    status: "partial",
    note: "rokki_list_tools returns enough for browsing; no separate detail tool. Acceptable.",
    priority: "low",
  },
  {
    resource: "tools",
    action: "Register / publish tool",
    apiEndpoints: ["POST /v1/tools"],
    mcpTool: "rokki_register_tool",
    status: "present",
    note: "",
  },
  {
    resource: "tools",
    action: "Invoke tool",
    apiEndpoints: ["POST /v1/tools/:slug/invoke"],
    mcpTool: "rokki_call_tool",
    status: "present",
    note: "",
  },

  // ----- approvals -----
  {
    resource: "approvals",
    action: "List approvals",
    apiEndpoints: ["GET /v1/approvals"],
    mcpTool: null,
    status: "missing",
    note: "AI agent that triggers approval-required actions has no way to check status without polling REST.",
    priority: "medium",
  },
  {
    resource: "approvals",
    action: "Resolve approval",
    apiEndpoints: ["POST /v1/approvals/:id"],
    mcpTool: null,
    status: "admin-only",
    note: "Approving on behalf of someone else is exactly what we DO NOT want via MCP. Keep cookie-only.",
  },

  // ----- calendar -----
  {
    resource: "calendar",
    action: "Connect provider",
    apiEndpoints: ["POST /v1/calendar/connect/:provider"],
    mcpTool: null,
    status: "admin-only",
    note: "OAuth flow is browser-only.",
  },
  {
    resource: "calendar",
    action: "OAuth callback",
    apiEndpoints: ["GET /v1/calendar/callback/:provider"],
    mcpTool: null,
    status: "admin-only",
    note: "Browser redirect target.",
  },
  {
    resource: "calendar",
    action: "Manage connection",
    apiEndpoints: ["DELETE /v1/calendar/connections/:id"],
    mcpTool: null,
    status: "missing",
    note: "User might want to disconnect via MCP.",
    priority: "low",
  },

  // ----- drawings -----
  {
    resource: "drawings",
    action: "List annotations",
    apiEndpoints: ["GET /v1/drawings/:fileId/annotations"],
    mcpTool: null,
    status: "missing",
    note: "Construction-vertical: AI walking permit drawings should read existing annotations.",
    priority: "high",
  },
  {
    resource: "drawings",
    action: "Create annotation",
    apiEndpoints: ["POST /v1/drawings/:fileId/annotations"],
    mcpTool: null,
    status: "missing",
    note: "AI placing markup on a drawing.",
    priority: "high",
  },
  {
    resource: "drawings",
    action: "Edit/delete annotation",
    apiEndpoints: [
      "PATCH /v1/drawings/annotations/:id",
      "DELETE /v1/drawings/annotations/:id",
    ],
    mcpTool: null,
    status: "missing",
    note: "Companion to create.",
    priority: "medium",
  },

  // ----- share-links -----
  {
    resource: "share-links",
    action: "Get share link target",
    apiEndpoints: ["GET /v1/share/:token"],
    mcpTool: null,
    status: "admin-only",
    note: "Public unauthenticated endpoint; not an MCP concern.",
  },
  {
    resource: "share-links",
    action: "Manage share link",
    apiEndpoints: ["DELETE /v1/share-links/:id"],
    mcpTool: null,
    status: "missing",
    note: "Companion to file share-link create gap.",
    priority: "low",
  },

  // ----- tokens / api-keys -----
  {
    resource: "tokens",
    action: "List access tokens",
    apiEndpoints: ["GET /v1/me/tokens"],
    mcpTool: null,
    status: "admin-only",
    note: "Token mgmt should not be MCP-driven (chicken-and-egg, plus security).",
  },
  {
    resource: "tokens",
    action: "Create / revoke token",
    apiEndpoints: ["POST/DELETE /v1/me/tokens"],
    mcpTool: null,
    status: "admin-only",
    note: "Same — keep out of MCP.",
  },
  {
    resource: "api-keys",
    action: "List BYOK keys",
    apiEndpoints: ["GET /v1/me/api-keys"],
    mcpTool: null,
    status: "admin-only",
    note: "Sensitive credential mgmt; UI-only.",
  },
  {
    resource: "api-keys",
    action: "Add / remove BYOK keys",
    apiEndpoints: ["POST/DELETE /v1/me/api-keys"],
    mcpTool: null,
    status: "admin-only",
    note: "Sensitive credential mgmt; UI-only.",
  },

  // ----- flags / announcements -----
  {
    resource: "flags",
    action: "Get my flag values",
    apiEndpoints: ["GET /v1/me/flags"],
    mcpTool: null,
    status: "missing",
    note: "MCP clients might want to know which features are gated for them.",
    priority: "low",
  },
  {
    resource: "announcements",
    action: "List announcements",
    apiEndpoints: ["GET /v1/me/announcements"],
    mcpTool: null,
    status: "missing",
    note: "Useful for AI to surface relevant ops messages.",
    priority: "low",
  },
  {
    resource: "announcements",
    action: "Dismiss announcement",
    apiEndpoints: ["POST /v1/me/announcements/:id/dismiss"],
    mcpTool: null,
    status: "missing",
    note: "Companion to list.",
    priority: "low",
  },

  // ----- vendors -----
  // covered under spaces above

  // ----- depth modules -----
  // covered under terminals above

  // ----- health -----
  {
    resource: "health",
    action: "Health check",
    apiEndpoints: ["GET /v1/health"],
    mcpTool: null,
    status: "admin-only",
    note: "Ops endpoint; no MCP value.",
  },

  // ----- admin -----
  {
    resource: "admin",
    action: "All /v1/admin/* endpoints",
    apiEndpoints: ["GET/POST/PATCH/DELETE /v1/admin/**"],
    mcpTool: null,
    status: "admin-only",
    note: "Platform-admin surface. Per spec these are intentionally not MCP-exposed.",
  },

  // ----- MCP-only AI conveniences -----
  {
    resource: "terminals",
    action: "Summarize terminal (LLM)",
    apiEndpoints: [],
    mcpTool: "rokki_summarize_terminal",
    status: "present",
    note: "MCP-only — uses sampling. Intentional, no REST equivalent needed.",
  },
  {
    resource: "terminals",
    action: "Draft client update (LLM)",
    apiEndpoints: [],
    mcpTool: "rokki_draft_update",
    status: "present",
    note: "MCP-only — uses sampling. Intentional.",
  },

  // ----- markets -----
  // The 9 shipped rokki_markets_* tools cover the core read/manage loop
  // (quote, search, watchlist add/remove, portfolio add-lot + performance,
  // alert list/create). The remaining data + management endpoints exist in
  // REST but have no MCP equivalent yet — tracked here as the gap backlog.
  {
    resource: "markets",
    action: "Get a quote",
    apiEndpoints: ["GET /v1/markets/quote/:symbol"],
    mcpTool: "rokki_markets_quote",
    status: "present",
    note: "",
  },
  {
    resource: "markets",
    action: "Batch quotes for a watchlist",
    apiEndpoints: ["GET /v1/markets/quotes"],
    mcpTool: null,
    status: "missing",
    note: "rokki_markets_quote fetches one symbol; no batch tool. Low priority — agents can loop.",
    priority: "low",
  },
  {
    resource: "markets",
    action: "Search symbols",
    apiEndpoints: ["GET /v1/markets/search"],
    mcpTool: "rokki_markets_search",
    status: "present",
    note: "",
  },
  {
    resource: "markets",
    action: "List watchlists",
    apiEndpoints: ["GET /v1/markets/watchlists"],
    mcpTool: "rokki_markets_watchlists",
    status: "present",
    note: "",
  },
  {
    resource: "markets",
    action: "Add symbol to watchlist",
    apiEndpoints: ["POST /v1/markets/watchlists", "POST /v1/markets/watchlists/:id/symbols"],
    mcpTool: "rokki_markets_watchlist_add",
    status: "present",
    note: "Tool creates the watchlist if it doesn't exist, then adds the symbol.",
  },
  {
    resource: "markets",
    action: "Remove symbol from watchlist",
    apiEndpoints: ["DELETE /v1/markets/watchlists/:id/symbols"],
    mcpTool: "rokki_markets_watchlist_remove",
    status: "present",
    note: "",
  },
  {
    resource: "markets",
    action: "Rename / reorder watchlist",
    apiEndpoints: ["PATCH /v1/markets/watchlists/:id"],
    mcpTool: null,
    status: "missing",
    note: "Management action; no MCP tool. Low priority.",
    priority: "low",
  },
  {
    resource: "markets",
    action: "Delete watchlist",
    apiEndpoints: ["DELETE /v1/markets/watchlists/:id"],
    mcpTool: null,
    status: "missing",
    note: "Management action; no MCP tool. Low priority.",
    priority: "low",
  },
  {
    resource: "markets",
    action: "List portfolios",
    apiEndpoints: ["GET /v1/markets/portfolios"],
    mcpTool: null,
    status: "missing",
    note: "performance tool takes a portfolio by name and auto-creates; no explicit list tool.",
    priority: "medium",
  },
  {
    resource: "markets",
    action: "Create / rename / delete portfolio",
    apiEndpoints: [
      "POST /v1/markets/portfolios",
      "PATCH /v1/markets/portfolios/:id",
      "DELETE /v1/markets/portfolios/:id",
    ],
    mcpTool: null,
    status: "missing",
    note: "add-lot auto-creates a portfolio; explicit lifecycle management is REST-only.",
    priority: "low",
  },
  {
    resource: "markets",
    action: "Add a trade lot",
    apiEndpoints: ["POST /v1/markets/portfolios", "POST /v1/markets/portfolios/:id/lots"],
    mcpTool: "rokki_markets_portfolio_add_lot",
    status: "present",
    note: "Tool creates the portfolio if needed, then records the lot.",
  },
  {
    resource: "markets",
    action: "List / delete trade lots",
    apiEndpoints: [
      "GET /v1/markets/portfolios/:id/lots",
      "DELETE /v1/markets/portfolios/:id/lots/:lotId",
    ],
    mcpTool: null,
    status: "missing",
    note: "Lot ledger editing is REST-only. Low priority.",
    priority: "low",
  },
  {
    resource: "markets",
    action: "Portfolio performance",
    apiEndpoints: ["GET /v1/markets/portfolios/:id"],
    mcpTool: "rokki_markets_portfolio_performance",
    status: "present",
    note: "Computes positions + unrealized P/L from live quotes.",
  },
  {
    resource: "markets",
    action: "List price alerts",
    apiEndpoints: ["GET /v1/markets/alerts"],
    mcpTool: "rokki_markets_alerts",
    status: "present",
    note: "",
  },
  {
    resource: "markets",
    action: "Create price alert",
    apiEndpoints: ["POST /v1/markets/alerts"],
    mcpTool: "rokki_markets_alert_create",
    status: "present",
    note: "",
  },
  {
    resource: "markets",
    action: "Toggle / modify / delete alert",
    apiEndpoints: ["PATCH /v1/markets/alerts/:id", "DELETE /v1/markets/alerts/:id"],
    mcpTool: null,
    status: "missing",
    note: "Alert editing/removal is REST-only. Medium priority — agents create but can't tidy.",
    priority: "medium",
  },
  {
    resource: "markets",
    action: "Candle / chart series",
    apiEndpoints: ["GET /v1/markets/candles/:symbol"],
    mcpTool: "rokki_markets_candles",
    status: "present",
    note: "OHLC summary via Twelve Data (needs TWELVEDATA_API_KEY).",
  },
  {
    resource: "markets",
    action: "Company news",
    apiEndpoints: ["GET /v1/markets/news/:symbol"],
    mcpTool: "rokki_markets_news",
    status: "present",
    note: "",
  },
  {
    resource: "markets",
    action: "Company profile / fundamentals",
    apiEndpoints: ["GET /v1/markets/profile/:symbol"],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool. Medium priority.",
    priority: "medium",
  },
  {
    resource: "markets",
    action: "Market movers",
    apiEndpoints: ["GET /v1/markets/movers"],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool for gainers/losers/active. Medium priority.",
    priority: "medium",
  },
  {
    resource: "markets",
    action: "Financial statements",
    apiEndpoints: ["GET /v1/markets/financials/:symbol"],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool. Medium priority.",
    priority: "medium",
  },
  {
    resource: "markets",
    action: "Market overview board",
    apiEndpoints: ["GET /v1/markets/overview"],
    mcpTool: "rokki_markets_overview",
    status: "present",
    note: "MCP returns an indices + sectors snapshot (subset of the REST board).",
  },
  {
    resource: "markets",
    action: "Earnings calendar",
    apiEndpoints: ["GET /v1/markets/calendar"],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool. Medium priority.",
    priority: "medium",
  },
  {
    resource: "markets",
    action: "Stock screener",
    apiEndpoints: ["POST /v1/markets/screener"],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool to screen by price/%/market-cap. Medium priority.",
    priority: "medium",
  },
  {
    resource: "markets",
    action: "FX convert",
    apiEndpoints: ["GET /v1/markets/fx"],
    mcpTool: null,
    status: "missing",
    note: "No MCP tool. Low priority.",
    priority: "low",
  },
  {
    resource: "markets",
    action: "Options chain",
    apiEndpoints: ["GET /v1/markets/options/:symbol"],
    mcpTool: null,
    status: "missing",
    note: "REST endpoint is a stub (paid feed required); no MCP tool. Low priority.",
    priority: "low",
  },
  {
    resource: "markets",
    action: "Evaluate price alerts (scheduled)",
    apiEndpoints: ["GET /v1/cron/evaluate-price-alerts", "POST /v1/cron/evaluate-price-alerts"],
    mcpTool: null,
    status: "admin-only",
    note: "Internal cron job (CRON_SECRET auth) that fans triggered alerts into notifications. Not user-facing.",
  },
];

/** Convenience grouping for the doc + page header. */
export function countByStatus(): Record<ParityStatus, number> {
  const out: Record<ParityStatus, number> = {
    present: 0,
    partial: 0,
    missing: 0,
    "admin-only": 0,
  };
  for (const r of PARITY_ROWS) out[r.status] += 1;
  return out;
}

/** Sorted unique resources for filter UI. */
export function uniqueResources(): Resource[] {
  return Array.from(new Set(PARITY_ROWS.map((r) => r.resource))).sort() as Resource[];
}
